###---------------
#GET
###---------------

###Get all recipes
GET http://localhost:1234/recipes

###---------------
###Filtros
###---------------

###Filtrar por titulo
GET http://localhost:1234/recipes?title=CARBOnara 

###Filtrar recetas que incluyan un ingrediente.
GET http://localhost:1234/recipes?ingredient=EGG

###Filtar por dificultad
GET http://localhost:1234/recipes?difficulty=EAS

###Filtrar por tiempo limite de preparación.
GET http://localhost:1234/recipes?time_lte=30`  


###Obtener una receta por ID.
GET http://localhost:1234/recipes/1a2b3c4d-0002-0000-0000-000000000002


###------------------
###     POST
###------------------
POST http://localhost:1234/recipes
Content-Type: application/json

{
"title": "New Recipe",
"ingredients": ["Ingredient1","Ingredient2"],
"instructions": "Tutorial step by step",
"time": 20,
"difficulty": "easy"
}

###-------------
###  PUT
###-------------

PUT http://localhost:1234/recipes/1a2b3c4d-0002-0000-0000-000000000002
Content-Type: application/json

{
    "title": "Chicken Curry con PUT",
    "ingredients": ["Chicken", "Onion", "Garlic", "Tomato", "Curry Powder", "Coconut Milk"],
    "instructions": "Cook onion and garlic, add chicken, spices, tomatoes, and coconut milk. Simmer until cooked.",
    "time": 45,
    "difficulty": "medium"
  }

###-------------
###  PATCH
###-------------
PATCH  http://localhost:1234/recipes/1a2b3c4d-0002-0000-0000-000000000002
Content-Type: application/json

{
    "title": "Updated Recipe",
    "time": 20
}

###------------------
###     DELETE
###------------------

##Eliminar receta por id
DELETE http://localhost:1234/recipes/1a2b3c4d-0002-0000-0000-000000000002